name: docker-compose.dev.yml - Healthcheck

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs: 
  docker:
    name: Run containers
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      NEXT_PUBLIC_BACKEND_DOMAIN: ${{ secrets.NEXT_PUBLIC_BACKEND_DOMAIN }}
      NEXT_PUBLIC_MAGIC_LINK_DOMAIN: ${{ secrets.NEXT_PUBLIC_MAGIC_LINK_DOMAIN }}
      NEXT_PUBLIC_STYTCH_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_STYTCH_PROJECT_ID }}
      NEXT_PUBLIC_STYTCH_SECRET: ${{ secrets.NEXT_PUBLIC_STYTCH_SECRET }}
      NEXT_PUBLIC_STYTCH_PROJECT_ENV: ${{ secrets.NEXT_PUBLIC_STYTCH_PROJECT_ENV }}
      NEXT_PUBLIC_STYTCH_PUBLIC_TOKEN: ${{ secrets.NEXT_PUBLIC_STYTCH_PUBLIC_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
            compose-file: "./docker-compose.dev.yml"