name: konfig-push-openapi-spec
on:
  push:
    branches:
      - main
jobs:
  konfig-push-openapi-spec:
    runs-on: ubuntu-latest
    env:
      CLI_VERSION: 1.0.210
    steps:
      - uses: actions/checkout@v3
      - name: Cache node_modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-konfig-push-build-${{ env.CLI_VERSION }}
      - name: Install Konfig CLI
        run: npm install -g konfig-cli@$CLI_VERSION
      - name: Push OpenAPI Spec
        run: konfig push -s ./packages/api/swagger/swagger-spec.json -o panoratech -r my-sdks
